// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1eLAxcBr73Vd-YqPu0wH4jNw8CKZNT4',
    appId: '1:747347541189:web:5508cc74ec84c3ae3704ac',
    messagingSenderId: '747347541189',
    projectId: 'reddit-clone-7b985',
    authDomain: 'reddit-clone-7b985.firebaseapp.com',
    storageBucket: 'reddit-clone-7b985.appspot.com',
    measurementId: 'G-TL675JK62V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-AUbEhuI17BTe--PXH2ehwXQnTNzD_-4',
    appId: '1:747347541189:android:e9acfbc69c3eebbd3704ac',
    messagingSenderId: '747347541189',
    projectId: 'reddit-clone-7b985',
    storageBucket: 'reddit-clone-7b985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2EP5IoyjJ6ik-xOzmv1LOL25EExG_bc',
    appId: '1:747347541189:ios:4c463b8227ac0f063704ac',
    messagingSenderId: '747347541189',
    projectId: 'reddit-clone-7b985',
    storageBucket: 'reddit-clone-7b985.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2EP5IoyjJ6ik-xOzmv1LOL25EExG_bc',
    appId: '1:747347541189:ios:c5c4279b553c35e43704ac',
    messagingSenderId: '747347541189',
    projectId: 'reddit-clone-7b985',
    storageBucket: 'reddit-clone-7b985.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
